title: 'Learn to Code with BJS'
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: Lessons
    link: 'lessons/'
  - name: Strategy
    link: 'strategy/'
  - name: Resources
    link: 'resources/'
  - name: Makers All
    link: 'https://makersall.org/'

