title: 'Playful Coding'
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  # - name: Strategy
    # link: 'strategy/'
  - name: Creative DataViz
    link: 'dataviz/'

  - name: Intro to Coding
    link: 'lessons/'
  # - name: Resources
    # link: 'resources/'
  - name: Makers All
    link: 'https://makersall.org/'

